name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  packages:
    runs-on: ubuntu-24.04
    container:
      image: debian:bullseye-slim@sha256:e5b6442dd2e9684cf5e87d8338b5968f3b348636fc0be6d7850a381e3731a2bd
    steps:
      - name: Check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install build tools
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends build-essential dpkg-dev gcc-arm-linux-gnueabihf libc6-dev-armhf-cross

      - name: Build and test
        run: make clean all test

      - name: Build distribution packages
        run: make packages

      - name: Inspect Debian packages
        run: |
          dpkg-deb --info dist/i2ckiss-ng_*_amd64.deb
          dpkg-deb --info dist/i2ckiss-ng_*_armhf.deb
          cd dist
          sha256sum --check SHA256SUMS

      - name: Upload distribution packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: i2ckiss-ng-${{ github.sha }}
          path: dist/
          if-no-files-found: error
